### ISSUE TITLE
Add enrichers for conditions and movement to system (enhancement)

### ISSUE THREAD

**Issue by secondworldpublishing** [koboldpress/black-flag#673] opened 2024-07-24 05:02 UTC
e.g. &Reference[blinded]{blinded} and &Reference[dash][{dash}

~_Submitted by Clayton Thomson_

**Comment by arbron** [comment] 2024-07-25 02:19
Duplicate of https://github.com/koboldpress/black-flag/issues/368

**Closed by arbron** 2024-07-25 02:19 UTC
Labels: duplicate, system: enrichers
