### ISSUE TITLE
Feature Request: Choose Damage type on roll

### ISSUE THREAD

**Issue by GMToolbox** [koboldpress/black-flag#520] opened 2024-05-15 18:10 UTC
Some creatures and abilities let the creature or player choose a damage type when they roll the attack. A feature that allows you to select the damage types that can be used when setting up the attack or ability and then allow the user to select from that list in a drop down menu would be useful. Look at the Solodron's Melee Armament ability from page 245 of the Monster Vault as an example.

**Comment by arbron** [comment] 2024-06-07 20:22
Duplicate of https://github.com/koboldpress/black-flag/issues/402

**Closed by arbron** 2024-06-07 20:22 UTC
Labels: duplicate
